[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo	=	'vim-airline/vim-airline'
depends =	['vim-airline-themes']
hook_add= '''
   source ~/.config/nvim/plugins/vim-airline.vim
'''

[[plugins]]
repo	=	'vim-airline/vim-airline-themes'

[[plugins]]
repo	=	'ryanoasis/vim-devicons'

[[plugins]]
repo	=	'tomasr/molokai'

[[plugins]]
repo =  'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo =  'fatih/vim-go'

[[plugins]]
repo =  'Shougo/neosnippet.vim'

[[plugins]]
repo =  'Shougo/neosnippet-snippets'

[[plugins]]
repo =  'tpope/vim-surround'

[[plugins]]
repo =  'tyru/open-browser.vim'

[[plugins]]
repo =  'dhruvasagar/vim-table-mode'

[[plugins]]
repo =  'neoclide/coc.nvim'
build = './install.sh nightly'
[[plugins]]
repo =  'prabirshrestha/async.vim'
[[plugins]]
repo =  'prabirshrestha/vim-lsp'
[[plugins]]
repo =  'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo =  'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo =  'natebosch/vim-lsc'

[[plugins]]
repo =  'mbbill/undotree'
