[[Plugins]]
repo    =       'vim-airline/vim-airline'
depends =       ['vim-airline-themes']
hook_add = '''
   source ~/.config/nvim/plugins/vim-airline.vim
'''

[[plugins]]
repo    =       'vim-airline/vim-airline-themes'
