[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo	=	'vim-airline/vim-airline'
depends =	['vim-airline-themes']
hook_add= '''
   source ~/.config/nvim/plugins/vim-airline.vim
'''

[[plugins]]
repo	=	'vim-airline/vim-airline-themes'

[[plugins]]
repo	=	'ryanoasis/vim-devicons'

[[plugins]]
repo	=	'tomasr/molokai'

[[plugins]]
repo =  'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo =  'fatih/vim-go'

[[plugins]]
repo =  'w0rp/ale'
