[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo	=	'vim-airline/vim-airline-themes'

[[plugins]]
repo	=	'ryanoasis/vim-devicons'

[[plugins]]
repo	=	'tomasr/molokai'

[[plugins]]
repo =  'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo =  'Shougo/neosnippet.vim'

[[plugins]]
repo =  'Shougo/neosnippet-snippets'

[[plugins]]
repo =  'tpope/vim-surround'

[[plugins]]
repo =  'tyru/open-browser.vim'

[[plugins]]
repo =  'dhruvasagar/vim-table-mode'

[[plugins]]
repo =  'neoclide/coc.nvim'
build = './install.sh nightly'
on_i = 1
merged = '0'

[[plugins]]
repo =  'mbbill/undotree'
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'mattn/vim-goimports'
